### PR TITLE
more natural command structure

### PR DESCRIPTION
**Pull request by sqweelygig**
Enhanced the code to understand a greater, including more natural, range of time unit identifiers.

Signed-off-by: Andrew Lucas <andrewl@resin.io>

### CODE REVIEW

**Comment by hkdobrev** [comment]
Thanks, look good!

**Comment by hkdobrev** [comment]
Added you as a collaborator to the repo as per the [open open-source idea](https://github.com/Level/community/blob/master/CONTRIBUTING.md) and because we don't use this Hubot plugin much anymore.

**Comment by hkdobrev** [comment]
Released as [`0.1.5`](https://github.com/clippings/hubot-remind/releases/tag/0.1.5).

**Comment by sqweelygig** [comment]
Don't suppose you'd mind published the update to the npm package would you?
https://www.npmjs.com/package/hubot-remind
Thanks,
Andrew.

**Comment by hkdobrev** [comment]
@sqweelygig Thanks for reminding me! Done.

**Pull request merged**
